"""empty message

Revision ID: 0c026a52339f
Revises: 51f04011aa8f
Create Date: 2023-05-25 14:54:58.537220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c026a52339f'
down_revision = '51f04011aa8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('t1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t1',
    sa.Column('c1', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_table('test_item')
    op.drop_table('test_categories')
    # ### end Alembic commands ###
